"""empty message

Revision ID: 9e9681b1c6f7
Revises: 
Create Date: 2026-03-18 23:57:44.320803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9681b1c6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('numBaths', sa.Integer(), nullable=True),
    sa.Column('numRooms', sa.Integer(), nullable=True),
    sa.Column('ptype', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
